projectTitle = "CreativeWorks"
modId = "creative_works"
modVersion = "0.4.0"
group = "org.teamvoided"
githubRepo = "Teamvoided/CreativeWorks"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "TheEnderCore", "DuskAutumnStorm" ]
majorMinecraftVersion = "1.21"
minecraftVersion = "1.21.1"
fabricLoaderVersion = "0.16.10"
fabricApiVersion = "0.115.0+1.21.1"
fabricLangKotlinVersion = "1.11.0+kotlin.2.0.0"
license = "MIT"
modules = [ ]
modDescription = "Mod for mod devs and ppl who need to test things."
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ ]
disableKotlin = false

[mappings]
    # You have 6 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    type = "QUILT"
    version = "1.21.1+build.9"